"""
append_secret_model.py — Append-Secret Model (Section 5.3.2a).

Overview
--------
The append-secret model is a Modified-UI technique: the password the server
stores is not the raw user password but a transformed version that depends on
a short string supplied by the user (l) and a per-user random secret held
only by the honeychecker (r).

Registration
------------
1.  User submits password pwd and an extra string l (length 2–4).
2.  System generates a random secret r (length 3, never shown to the user).
3.  x = f(pwd || l || r)   where f is a collision-resistant one-way function
        (SHA-256 truncated to 5 hex chars is used here).
4.  Database stores H(pwd || x) — not H(pwd || l).
5.  Honeychecker stores (c(i), r) for this user via set_with_secret().
6.  Honeywords are generated by varying l while keeping r fixed.

Authentication
--------------
1.  User submits pwd and l.
2.  Server retrieves r from honeychecker via get_secret().
3.  Server recomputes x = f(pwd || l || r).
4.  Server reconstructs the stored form: pwd || x.
5.  Server locates this string in the sweetword list to get an index j.
6.  Server calls Check(username, j) on the honeychecker.
7.  Honeychecker returns True (sugarword) or False + alarm (honeyword).

Security properties
-------------------
- Perfect flatness.
- Strong DoS resistance: honeywords contain the same password prefix, only
  the appended hash fragment differs.
- Prevents BOTH MSIO and MSII attacks: r is chosen independently per site,
  so even if the user reuses pwd and l across sites, the stored values
  differ entirely.
- Typo-safe: Levenshtein distance ≥ 2 enforced (the appended hash fragment
  differs by only a few characters, so a threshold of 3 would be too strict).

Usability note (Section 5.3.2a)
--------------------------------
Users must memorise l in addition to their password.  For a single site this
adds only 2–4 characters.  Research (Bonneau & Schechter 2014; Blocki et al.
2015) shows humans can reliably memorise short random strings via spaced
repetition.  For multi-site deployment, single sign-on integration is
recommended so one l suffices.


Fixes applied:

  Gap 3 — fake l values used only alphanumeric characters:
    The user's real l can contain any printable character (the paper imposes
    no charset restriction, only a length of 2-4).  Generating fake l values
    from a strictly alphanumeric alphabet means the honeyword space is a
    strict subset of the real l space when the user picks a special character
    in their l.  This hurts flatness and gives an attacker information.

    Fix: fake l values are now drawn from the same full alphabet
    (ascii_letters + digits + _SPECIAL_CHARS) as the system secret r, which
    is a superset of any realistic user choice.

  Gap 4 — Levenshtein filter was ineffective and semantically wrong:
    All stored forms share the identical password prefix; only the 5-char hex
    suffix differs.  The maximum possible Levenshtein distance between any two
    stored forms is therefore 5.  With min_lev_dist=2 the filter almost never
    rejects anything, and with a higher threshold it would incorrectly discard
    valid honeywords.

    More importantly, the paper does not specify a Levenshtein filter for
    this model — typo-safety is handled *structurally*: a user who mistypes
    their password produces a completely wrong x value and will not match any
    entry in the sweetword list, so no false alarm is raised.  The filter was
    therefore both ineffective and theoretically unsound.

    Fix: the Levenshtein filter is removed entirely.  A simple duplicate /
    equality check replaces it, which is all that is needed to guarantee k
    distinct honeywords.
"""

from __future__ import annotations

import hashlib
import random
import string

from honeychecker import Honeychecker, SweetwordList
from frequency_db import _SPECIAL_CHARS

# Full character space for fake l values (fixes gap 3)
_L_ALPHABET = string.ascii_letters + string.digits + _SPECIAL_CHARS


def _compute_x(password, l, r):
    """x = f(pwd || l || r)  — SHA-256 truncated to 5 hex chars."""
    return hashlib.sha256((password + l + r).encode()).hexdigest()[:5]


def generate_honeywords_append_secret(username, password, user_extra,
                                       honeychecker, k=20):
    """
    Append-Secret Model — registration (Section 5.3.2a).

    Parameters
    ----------
    username     : registering user's identifier
    password     : the real user password
    user_extra   : user-supplied extra string l  (2-4 characters)
    honeychecker : Honeychecker — r is written here; never returned
    k            : total sweetwords (honeywords + 1 sugarword); default 20

    Returns
    -------
    SweetwordList  — entries are pwd||x (stored form), not raw passwords.

    Note: min_lev_dist parameter removed (fix for gap 4).  Typo-safety for
    this model is structural, not distance-based.
    """
    if not (2 <= len(user_extra) <= 4):
        raise ValueError(f"user_extra must be 2-4 characters; got {len(user_extra)}.")

    # System-generated per-user, per-site random secret r
    r = ''.join(random.choices(_L_ALPHABET, k=3))

    real_x      = _compute_x(password, user_extra, r)
    real_stored = password + real_x

    honeywords = []
    seen_l     = {user_extra}
    attempts   = 0
    max_attempts = k * 200   # generous — collisions are rare but possible

    while len(honeywords) < k - 1 and attempts < max_attempts:
        attempts += 1
        # FIX gap 3: draw fake l from the full alphabet, not just alphanumerics
        fake_l = ''.join(random.choices(_L_ALPHABET, k=len(user_extra)))
        if fake_l in seen_l:
            continue
        seen_l.add(fake_l)

        hw = password + _compute_x(password, fake_l, r)

        # FIX gap 4: simple duplicate / equality check only; no Levenshtein
        if hw == real_stored or hw in honeywords:
            continue

        honeywords.append(hw)

    warnings = []
    if len(honeywords) < k - 1:
        warnings.append(f"Only generated {len(honeywords)} honeywords (wanted {k-1}).")

    sugar_index = random.randint(1, len(honeywords) + 1)
    sweetwords  = honeywords[:sugar_index-1] + [real_stored] + honeywords[sugar_index-1:]

    # r is written to honeychecker here and never exposed to the caller
    honeychecker.set_with_secret(username, sugar_index, r)

    return SweetwordList(sweetwords=sweetwords, sugarword_index=sugar_index,
                         password_pattern='append-secret',
                         list_sizes={'r_len': 3, 'l_len': len(user_extra)},
                         warnings=warnings)


def authenticate_append_secret(username, submitted_password, submitted_extra,
                                sweetword_list, honeychecker):
    """
    Append-Secret Model — authentication (Section 5.3.2a).

    1. Retrieve r from honeychecker.
    2. Recompute x = f(submitted_pwd || submitted_l || r).
    3. Reconstruct the stored form: submitted_pwd || x.
    4. Locate it in the sweetword list to get position j.
    5. Call Check(username, j) on the honeychecker.
    """
    r = honeychecker.get_secret(username)
    if r is None:
        print(f"  [ERROR] No append-secret record for '{username}'.")
        return False

    candidate = submitted_password + _compute_x(submitted_password, submitted_extra, r)

    try:
        position = sweetword_list.sweetwords.index(candidate) + 1  # 1-based
    except ValueError:
        print(f"  [DENY] '{username}': submitted value not found in sweetword list.")
        return False

    return honeychecker.check(username, position)